language: ruby
rvm:
- 2.1
sudo: false
install:
- gem install bundler --no-rdoc --no-ri
- bundle install
- npm install remark-cli remark-lint remark-lint-sentence-newline
script:
- jekyll build
- ./node_modules/remark-cli/cli.js --frail articles/

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of
